### ISSUE TITLE
instal

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [hyperreality/American-British-English-Translator#15]
As far as I know _instal_ with a single **l** is neither UK nor US English:
https://github.com/hyperreality/American-British-English-Translator/blob/92fdb9a0980f8d47b0fc519e0b5b632ade7670b9/data/british_spellings.json#L846
https://github.com/hyperreality/American-British-English-Translator/blob/92fdb9a0980f8d47b0fc519e0b5b632ade7670b9/data/british_spellings.json#L849
https://github.com/hyperreality/American-British-English-Translator/blob/92fdb9a0980f8d47b0fc519e0b5b632ade7670b9/data/american_spellings.json#L840
https://github.com/hyperreality/American-British-English-Translator/blob/92fdb9a0980f8d47b0fc519e0b5b632ade7670b9/data/american_spellings.json#L843
See:
* [Cambdridge Dictionary](https://dictionary.cambridge.org/dictionary/english/install)
* [Oxford Learner's Dictionary](https://www.oxfordlearnersdictionaries.com/definition/english/install)

**Comment by hyperreality** [comment]
Agreed - according to Wiktionary it's a dated alternative spelling, it shouldn't be given as the standard for British English so I've removed it here https://github.com/hyperreality/American-British-English-Translator/commit/11ba3aa5b7d8650540ec60a3ee64286569bc4f0b
