### ISSUE TITLE
Include "stuffed animal" in different meanings list

### ISSUE THREAD

**Issue by jpgoldberg** [hyperreality/American-British-English-Translator#6]
In American English a "stuffed animal" is a what I believe in Britain is called a "plush toy." If I understand correctly, in BE "stuffed animal" is the result of taxidermy on what was once a live animal.

**Comment by hyperreality** [comment]
Good catch and that's an interesting variance, although in Britain we'd probably call this a "cuddly toy" or "soft toy". I'll add this to the wordlists later and do a much-needed update after almost a half-decade of neglect!

**Comment by hyperreality** [comment]
https://github.com/hyperreality/American-British-English-Translator/commit/240d12e05f0273d6d4b0c551c81f00b1de375a51
